### ISSUE TITLE
[Feature Request] Daycare Info in Item List

### ISSUE THREAD

**Issue by JumperK** [jshepler/jshepler.ngu.mods#10]
Before I begin, I'd like to say thanks for this mod; it's actually helped quite a bit.

I've created a file that I use to fill out any info in the game - which is only the item list so far; it has more information than the in-game Item List - using the wiki as a reference, which includes the Item Daycare level-up time.

If it is at all possible, could you add how long the item takes to level up in the Item List?
Like, maybe using SHIFT while hovering over the item, similar to how it shows where the item drops while holding ALT?

**Comment by jshepler** [comment]
Items currently in the daycare have that now. Hover mouse over an item in daycare and it will show the current time per level and holding the alt key shows a short breakdown of that time.

Additionally, vanilla only shows the daycare speed modifiers in stat breakdowns (misc), I added the daycare time modifiers to it.

I know it's not quite what you're asking - you want to see that info in the item list and it might be nice to know before putting an item in daycare, but I'm happy with how it is now.

I'll keep it in mind, though. If I change my mind in the future, I'll re-open this.
