### ISSUE TITLE
Can't load save file on v1.15

### ISSUE THREAD

**Issue by archraziel** [jshepler/jshepler.ngu.mods#11]
Using last jshepler version 1.15 

When I click "On To The Game"

![image](https://github.com/user-attachments/assets/e42ee2a6-a3bc-433f-8c92-7514dde799c8)
 
 
Takes me back too this screen

![image](https://github.com/user-attachments/assets/519fcccc-2a13-4bd0-8816-1ae485a40d4c)

And I can't load my save. 

I am able to load it when I revert back to 1.14

**Comment by jshepler** [comment]
Attach your save and I'll look into it.

**Comment by archraziel** [comment]
[NGUSave-Build-1260-November-01-17-21.txt](https://github.com/user-attachments/files/17602514/NGUSave-Build-1260-November-01-17-21.txt)

If I try to load file form computer, it loads but I get this message

![image](https://github.com/user-attachments/assets/b99d96df-fc67-41ac-859d-b7527e62e353)

**Comment by jshepler** [comment]
fixed in 1.15.1
