### ISSUE TITLE
[Feature Request] Blood Magic Multiplier

### ISSUE THREAD

**Issue by luxuriosity** [jshepler/jshepler.ngu.mods#6]
Suggestion:
Adding the Blood Magic Multiplier to the Blood Magic or Misc. Stats Menu

**Comment by jshepler** [comment]
Not sure what multiplier you're referring to, I assume blood gain?

I believe there is only one modifier to ritual speed and that's a set completion late sad. Not really much need to show that.

If you're referring to something else, please elaborate.

**Comment by luxuriosity** [comment]
Yes I meant the Blood Gain, sorry for the confusion

**Comment by jshepler** [comment]
added in 1.14
