### ISSUE TITLE
[Feature Request] Card Management (Sorting/Auto-Yeeting)

### ISSUE THREAD

**Issue by djuniah** [jshepler/jshepler.ngu.mods#7]
First and foremost, thank you SO MUCH for this mod.  It makes such a QOL difference!

Secondly, i find that one of my biggest wastes of time at my current point in the game is card management.  Being able to sort them by quality, or even a way to "yeet all below a certain quality" would go a long way to helping with that. I am a dev myself (mainly C#/Unity) and could help look into this if you were interested in submissions.  Based on what you know about the codebase, how difficult do you think something like this would be?

**Comment by jshepler** [comment]
I don't really take feature requests. I'm open to ideas and if something interests me, I'll probably do it. Almost all of the mods I did for myself and I'm basically sharing them as-is. A couple (like twitch integration) I did for friends, and I've added a couple options to disable some things, but for the most part I'm the target audience.

I'm currently open to submissions, but I've never done that before so it's possible I'll change my mind about that if I start having a problem with it. Of course, people are always free to modify the source for themselves. I know of some who have done that.

That all said, I won't add just anything. I won't take blatant cheats (like infinite gold/exp/pp/qp/ap or god mode), but the line between what is and is not acceptable is different for everyone. For myself, I don't like babysitting the game, so things like auto manual questing is just fine for me. Or if something is annoying enough, like cooking. But I don't want to automate too much, I still want to have daily interaction with most of the features.

Auto casting/yeeting cards is an obvious redundant thing to automate and I've thought about doing it a couple times. It's right on the line for me. It's not babysitting and not overly annoying, but does get boring after a while. However, when I think about things like not casting undesired cards (like hack cards after being done with hacks), or things that have affected my casting decisions (low mayo, low tier, low bonus, the feature being boosted, etc.), chonkers, end cards, and so on - proper configuration can get pretty complicated. Especially if you're going to make it flexible enough to suit everyone.

And then I realize that making those decisions is why I still like having that interaction with cards, so I choose not to automate it.

However, if you want to do it, I'll definitely consider your submission. It shouldn't be all that difficult. I've already hooked into when cards area added so I can move regular cards to be before chonkers. You should be able to easily extend that to do what you want.

**Comment by djuniah** [comment]
Hi jshepler, I appreciate the detailed response and apologies for the late reply, I didn't see the notification about the message.  Totally understandable about only wanting to add in things that are of interest to you, I maintain a project where I have similar rules.  If I do get around to implementing it, I'll create a pull request here so that you can take a look but totally understand if it's not something you want to include.

**Comment by jshepler** [comment]
I was thinking more on this and realized the issues I have is around auto-casting, which isn't what you were asking for. Auto sort/yeet is fine and I did a super basic implementation that will be in the next update, but here's the first iteration of the class if you want to help me test it or improve it. Obviously comment out the option checks and hard-code the max rarity. 

```
using System.Linq;
using HarmonyLib;
using UnityEngine;

namespace jshepler.ngu.mods
{
    [HarmonyPatch]
    internal class AutoCards
    {
        // skip doing auto sort/yeet when an auto yeet is in progress to guard against chaning the list while auto-yeeting
        private static bool _autoYeetInProgress = false;

        [HarmonyPostfix
            , HarmonyPatch(typeof(CardsController), "addCard")
            , HarmonyPatch(typeof(CardsController), "addChonkerCard")]
        private static void CardsController_addCards_postfix()
        {
            if (_autoYeetInProgress)
                return;

            if (Options.AutoCards.AutoYeet.Value == true)
            {
                _autoYeetInProgress = true;
                yeetCards();
                _autoYeetInProgress = false;
            }

            if (Options.AutoCards.AutoSort.Value == true)
                sortCards();
        }

        [HarmonyPostfix, HarmonyPatch(typeof(CardsController), "Update")]
        private static void CardsController_Update()
        {
            if (!Plugin.Character.InMenu(Menu.Cards))
                return;

            if (Input.GetKeyDown(KeyCode.S))
                sortCards();

            if (Input.GetKeyDown(KeyCode.Y))
                yeetCards();
        }

        private static void yeetCards()
        {
            var character = Plugin.Character;
            var maxRarity = Options.AutoCards.MaxYeetRarity.Value;
            var cards = character.cards.cards;
            var index = cards.Count;

            while (index > 0)
            {
                if (cards[--index].cardRarity <= maxRarity)
                {
                    Plugin.LogInfo($"auto yeeted a {cards[index].cardRarity} card");
                    character.cardsController.trashCard(index);
                }
            }
        }

        private static void sortCards()
        {
            var character = Plugin.Character;
            var cards = character.cards.cards;

            cards.Sort(cardComparer);

            character.cards.cards = cards;
            character.cardsController.updateDeckPods();
            character.cardsController.updateDeckButtons();
        }

        private static int cardComparer(Card a, Card b)
        {
            if (a.cardRarity != b.cardRarity)
                return a.cardRarity.CompareTo(b.cardRarity);

            if (a.bonusType != b.bonusType)
                return a.bonusType.CompareTo(b.bonusType);

            return a.manaCosts.Sum().CompareTo(b.manaCosts.Sum());
        }
    }
}
```

**Comment by djuniah** [comment]
Yeah the idea came from the repetitive loop of "look through all of my cards for anything crappy/bad tier and then yeet them".  The toast/notification pop-ups actually become an obstacle when doing it for a large number of them, as they cover up the right side so it becomes a little difficult to see the full list.  I figured that having them sorted by quality would quickly allow me to hit the yeet button without worrying about it so much.  The sort was the real time-saver IMO, but auto-yeet (and by that i mean a "yeet anything less than X quality") would be a "nice to have" without being too cheat-y since it just replaces me taking a minute or two to sort through it all each time.  

As far as the code you posted, that all looks pretty good to me.  I'm quite new to the NGU codebase, so my knowledge there is limited, but the overall logic seems sound.  I did start poking around to get a general understanding of it the other day and I found the way that BepinX/HarmonyX hooks into unity's Update/etc. functions to be quite interesting.  Thanks again for looking into this, I appreciate it!!!

**Comment by jshepler** [comment]
> The toast/notification pop-ups actually become an obstacle when doing it for a large number of them, as they cover up the right side so it becomes a little difficult to see the full list.

Just an FYI, the toasts hide when moused over and an update or two ago, I added keybinds for working with the cards. You can position your mouse to cause the toasts to be hidden and use enter/delete/space keys.

**Comment by djuniah** [comment]
Ah, I must have missed that in the notes, thanks for the reminder, that is quite handy.

**Comment by jshepler** [comment]
added in 1.14
