### ISSUE TITLE
[Feature Request]Major Quest Timer

### ISSUE THREAD

**Issue by luxuriosity** [jshepler/jshepler.ngu.mods#8]
It is a bit annoying to see how long it takes for you to gain a major quest, maybe displaying it below the timer as 'You gain a Major Quest every x:xx hours' would be cool

**Comment by jshepler** [comment]
Nah... I don't think it'd be very useful as there are only 2 modifiers and it doesn't change how many majors you get per day all that much. Base is 28,200 seconds, which is 3.06 majors per day. With both modifiers (AP purchase and fad set), it's 20,304 seconds, which is 4.25 majors per day.

**Comment by jshepler** [comment]
Changed my mind, will be in next update.

**Comment by jshepler** [comment]
added in 1.15
