### ISSUE TITLE
Feature Request (wish queue levels)

### ISSUE THREAD

**Issue by Bibense** [jshepler/jshepler.ngu.mods#9]
Thanks for the mod, using it wholeheartedly. Ekkodra in discord. 

My request is about the queue in the wishes. A lot of wishes EMR PCB especially has 10 levels. I wonder if it is possible to add levels in the queue. i.e. now my bars has 4,4,4,5,6,7... max hrs to finish. I wish to lvl up all my EMR bars no more than 1st level. But the queue won't jump to another wish without finishing all 10 lvls. I am not a coder and don't know whether it is something hard or not and you probably have a plan for some other features in your agenda. But this one is really helps a lot when planning wishes. 

Thanks again for the mod.

**Comment by jshepler** [comment]
Thanks for the idea. It's interesting but I think I'm going to pass for now. I'll keep it mind and will re-open this if I change my mind down the road.

**Comment by jshepler** [comment]
Changed my mind.

Testing an idea on how to do wish target levels in the queue. If it goes well, this will be in next update.

**Comment by jshepler** [comment]
Nope, failed.

The idea I had wasn't thought through very well. I thought it was as simple as adding targets to the queue, but it's not. I forgot why I had passed before - I'd have to re-write the queue system and I'm not inclined to do that just now.

**Comment by jshepler** [comment]
added in 1.16
